### ISSUE TITLE
Expirating Date validation

### ISSUE THREAD

**Issue by renannery** [cooltechworks/CreditCardView#8]
Congrats for the library, I really like the idea to bring some reality to android views.

I've been working on mCommerces companies for a while and I'd like to share a situation that I was face in this field.

We, as android developers or client developer, can not block the user to input a expired date in the field. This is a kind of business logic that should be handle in the backend. Sometimes the payment brand (visa, amex, mastercard, etc) will accept the purchase, even if the credit card is already expired.

**Comment by cooltechworks** [comment]
Thanks Renannery for bringing in to the notice and I understand it will be business requirement whether to block/allow validation on cards. I will make changes to include additional flags to control validation.

Thanks,
Harish

**Comment by cooltechworks** [comment]
Fixed in 	fb660a1 and README is updated here :  5b534a3

**Comment by renannery** [comment]
👍
